---


- hosts: all
  become: true
  tasks:

  - name: dnf update the system
    dnf:
      name: "*"
      state: latest

  
  - name: install httpd package 
    dnf:
      name: httpd
      state: latest 
